spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/local_ideas2it
    username: root
    password: I22266@i2i
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
    
welcome:
  message: DEV env- Welcome to Spring cloud config server
