
spring:
  application:
    name: user
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_ideas2it
    username: ${dbuser}
    password: ${dbpass}
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  cloud:
    vault:
      host: localhost
      port: 8200
      scheme: http
      token: hvs.yNa7JQhmBnLb7Z7aEaZ6Cbor
      kv:
        enabled: true
        profile-separator: /
        backend: kv # env based profiles are created inside kv in vault
  cache:
    type: redis
  config:
    import: 
    - vault://
