
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_ideas2it
    username: root
    password: I22266@i2i
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  cloud:
    vault:
      host: localhost
      port: 8200
      scheme: http
      token: hvs.0d61KLdFpo187elNDaVuMrRP
  cache:
    type: redis
