
spring:
  application:
    name: user
  config:
    import: 
    - vault://
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_ideas2it
    username: ${dbuser}
    password: ${dbpass}
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  cache:
    type: redis

